version: "3"
include:
  - proxy.yaml
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: on-failure
services:
  db:
    image: mysql:8
    <<: [*env_file, *restart]
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    #проверка работоспособности mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 60s
      interval: 5s
      timeout: 5s
      retries: 10
  web:
    depends_on:
      #Проверяем, что sql полностью стартовал. Иначе сразу после старта множество перезапусков и ошибки при обращении
      db:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile.python

    <<: [*env_file, *restart]
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db


